date_to_mjd – jacchia-roberts-fortran
date_to_mjd Subroutine
5 statements
Source File
public pure subroutine date_to_mjd(year, month, day, mjd)
Convert calendar date to Modified Julian Date (MJD)
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in) :: year
integer(kind=ip), intent(in) :: month
integer(kind=ip), intent(in) :: day
real(kind=dp), intent(out) :: mjd
Calls
Called by
Source Code
   pure subroutine date_to_mjd(year, month, day, mjd)
      integer(ip), intent(in) :: year, month, day
      real(dp), intent(out) :: mjd
      ! Convert JDN to MJD at midnight (00:00 UTC)
      ! JDN is at noon, so JDN - 0.5 gives midnight
      ! MJD = JD - 2400000.5 = (JDN - 0.5) - 2400000.5 = JDN - 2400001.0
      mjd = real(julian_day(year, month, day) - 2400001, dp)
   end subroutine date_to_mjd
Call graph
date_to_mjd calls julian_day
sw_init calls date_to_mjd
jr_init calls sw_init